apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-volume
  namespace: 2-2
spec:
  selector:
    matchLabels:
      app: test-volume
  replicas: 1
  template:
    metadata:
      labels:
        app: test-volume
    spec:
      nodeSelector:
         kubernetes.io/hostname: kuber
      containers:
      - name: busybox
        image: busybox:latest
        command: ['sh', '-c', 'mkdir -p /out/logs && while true; do echo "hello-world! - $(date)" >> /out/logs/success.txt; sleep 5; done']
        volumeMounts:
        - name: volume
          mountPath: /out/logs
      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'tail -f /out/logs/success.txt']
        volumeMounts:
        - name: volume
          mountPath: /out/logs
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: pvc-vol